### ISSUE TITLE
Why is the carbon binary so large?

### ISSUE THREAD

**Issue by devhaozi** [dromara/carbon#249]
![image](https://github.com/user-attachments/assets/a5ca594f-67e0-4512-bb18-8a3991e1f7b3)

This is the dependency graph obtained by analyzing the go program using https://gsa.zxilly.dev/, which shows that carbon takes up a lot of space.

**Comment by devhaozi** [comment]
![image](https://github.com/user-attachments/assets/2df621f1-718a-45b5-8de7-44180cc17042)

The results of using tui mode analysis show that these structures and functions take up a lot of space.

**Comment by gouguoyin** [comment]
Because each call creates a new `Carbon` object, it is possible to consider returning a pointer to reuse the object, thereby reducing the pressure of memory allocation and garbage collection. However, the entire project needs to be refactored, which is too destructive.

**Comment by gouguoyin** [comment]
Do you have any good optimization plans?

**Comment by devhaozi** [comment]
> Do you have any good optimization plans?

No, maybe this can be optimized in future v3 version.
