### ISSUE TITLE
When parsing database data, should `[]byte` always be parsed???

### ISSUE THREAD

**Issue by shuqingzai** [dromara/carbon#251]
在使用一些复杂的 SQL 时，如：时间分组、自定义字段等，非基础类型的字段值通常会被设置为 `[]byte` ，我们需要自行实现 `Scanner` 接口解析其值，但是在 carbon 中，只解析值为 `time.Time` 类型，并未解析 `[]byte` ，导致使用复杂 SQL 时，无法实现解析

See: https://github.com/golang-module/carbon/blob/165bda517b50bc3fd41f952c0d53c7478fbf2db3/database.go#L10-L21

![image](https://github.com/user-attachments/assets/5cac6bf2-684a-48dd-9e73-35efcdb3d3c8)

**Comment by gouguoyin** [comment]
Please provide a complex SQL example
