### ISSUE TITLE
Make README Japanese translations easier to read

### ISSUE THREAD

**Issue by You-saku** [dromara/carbon#257]
Hi！ I'm you-saku. I have a suggestion regarding README.
Now, Japanese translation is unnatural in some parts. I would like to re-translate and improve the README to make it easier to read by a Japanese person such as me.

How do you like it?

**Comment by gouguoyin** [comment]
The current Japanese version relies on AI software. If you could translate it, I would greatly appreciate it.

**Comment by You-saku** [comment]
Thanks for the quick reply. 
 I would love to do this on my end. 👍

**Comment by You-saku** [comment]
@gouguoyin 
I have created pull request. 👍 
https://github.com/dromara/carbon/pull/259
