### ISSUE TITLE
Why can't get "github.com/dromara/carbon/v2"

### ISSUE THREAD

**Issue by You-saku** [dromara/carbon#258]
I wanna use "github.com/dromara/carbon/v2" in docker environment. I created docker(go), and try to install  "github.com/dromara/carbon/v2". I can't get  "github.com/dromara/carbon/v2".
<img width="906" alt="スクリーンショット 2024-11-23 23 54 44" src="https://github.com/user-attachments/assets/9ebe5ca9-ceff-4b94-a2a2-3f460086db7a">

But, I can "github.com/golang-module/carbon/v2".
Why I can't get "github.com/dromara/carbon/v2" in docker environment

## My Environment
 - OS: MacOS Sequia
 - CPU: Intel CPU
 - Docker Desktop version: 4.34.3
 - docker compose version: 2.92.2
 - docker version: 27.2.0
 - using golang image(docker): FROM golang:1.22

**Comment by gouguoyin** [comment]
`github.com/dromara/carbon/v2` has not been released yet and is currently being used on `github.com/golang-module/carbon/v2`

**Comment by You-saku** [comment]
Thanks for the reply! I understand.
I will close this issue 🙏
