### ISSUE TITLE
Any interest in golangci-lint ?

### ISSUE THREAD

**Issue by ccoVeille** [dromara/carbon#264]
Are you interested in adding golangci-lint to your project and CI ?

https://github.com/golangci/golangci-lint

I could help.

**Comment by ccoVeille** [comment]
A very basic set of rules (such as these https://github.com/ccoVeille/golangci-lint-config-examples/tree/main/03-safe) detected 

24 issues:
* dupword: 1
* errcheck: 9
* gci: 3
* gosimple: 3
* govet: 1
* revive: 3
* staticcheck: 2
* unused: 2

If I go further with a lot of linters

472 issues:
* dupword: 1
* errcheck: 44
* gci: 10
* gocritic: 4
* gosec: 1
* gosimple: 18
* govet: 1
* perfsprint: 6
* revive: 215
* staticcheck: 2
* testifylint: 124
* unused: 2
* usestdlibvars: 44


I think you have room for improvements, and I could help

**Comment by gouguoyin** [comment]
If possible, thank you very much.

> Are you interested in adding golangci-lint to your project and CI ?
> 
> https://github.com/golangci/golangci-lint
> 
> I could help.

**Comment by ccoVeille** [comment]
sure

I would like to know what you guys prefer:
- activate golangci-lint in the CI now, but non-blocking
- activate golangci-lint in the CI now, but non-blocking, limited to code changed only
- activate golangci-lint in the CI now, blocking on new code, but non blocking for all code base.

The long term target is of course, blocking on all code base

We can start with a periodic task run that will report things. 

All these depends on the way golangci-lint reports will be welcomed by the maintainers.

So tell me, of course, I can set it up the way I would like to, but then maintainers and contributions could become temporarily more difficult

Also, there are many things to fix. I could fix them via PR, but I think it would be better if everyone could ramp up in writing better code.

My motto is somehow: Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.

**Comment by ccoVeille** [comment]
What are the next steps then?

I saw you activated it through the CI, the rolled back.

**Comment by gouguoyin** [comment]
Rollback is because I found that actions were not working.
