### ISSUE TITLE
不支持解析 7d 这样的Duration ?

### ISSUE THREAD

**Issue by chaseSpace** [dromara/carbon#272]
RT

**Comment by chaseSpace** [comment]
7d, 7m, 7y

**Comment by gouguoyin** [comment]
`AddDuration` and `SubDuration` methods support
<img width="836" alt="image" src="https://github.com/user-attachments/assets/bbb96e73-4a0a-4ed3-a79c-3d9c1e611000" />

**Comment by chaseSpace** [comment]
May be should have a enhanced api like `ParseDuration` in std time pkg.

**Comment by gouguoyin** [comment]
`ParseDuration` can be confusing, for example, does `7d` mean 7 days before or after today?

**Comment by gouguoyin** [comment]
For another example, does `7s` mean setting the seconds of the current time to 7, or 7 seconds after the current time?

**Comment by gouguoyin** [comment]
I think `Duration` is more suitable for `modifying` existing time rather than `parsing`.

**Comment by chaseSpace** [comment]
You may not have a correct understanding of the usage of the ` ParseDuration ` API in std time pkg. This API only has one parameter of string type, which represents the specific duration in string form ("time. duration" type). It only performs parsing and is independent of a certain point in time.

See examples:
```
package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
	"time"
)

func TestX(t *testing.T) {
	d, _ := time.ParseDuration("7m")
	assert.Equal(t, d, time.Minute*7)

	d, _ = time.ParseDuration("7h7s")
	assert.Equal(t, d, time.Hour*7+time.Second*7)

	d, err := time.ParseDuration("7d")
	t.Log(err) /// time: unknown unit "d" in duration "7d"
}
```

So i don't known why not support `d` of duration unit from std pkg. For now, i copied and modified the API of the standard library as a temporary method.

**Comment by gouguoyin** [comment]
All methods return a `carbon` object, which is an exact point in time. but `ParseDuration` returns a `Duration` object. What are the usage scenarios of `ParseDuration`?

**Comment by chaseSpace** [comment]
So, why does the API "time.ParseDuration" exist? Why am I here to talk to you?

**Comment by gouguoyin** [comment]
This is not a communication problem. I am trying to understand your specific usage scenario.
